# Local secrets store. Replace with your actual GCP Project ID when ready.
APIFY_TOKEN = "apify_api_Bq4oUTfVdymvgOOwEPERVb71f9ZcbJ2Q2Km0"
GCP_PROJECT_ID = "grand-bridge-406308"
GCP_DATASET_NAME = "social_media"
USE_MOCK_DB = false # Set to false to use true Google BigQuery